# Generated by Django 5.2 on 2025-08-31 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rules', to='event.eventtype')),
            ],
            options={
                'verbose_name': 'Quy tắc điểm',
                'verbose_name_plural': 'Quy tắc điểm',
                'db_table': 'point_rules',
                'unique_together': {('event_type', 'condition')},
            },
        ),
    ]
