# Generated by Django 5.2 on 2025-10-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_special',
        ),
    ]
